name: Coverage

on: [pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo +nightly llvm-cov --all-features --workspace --html
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: target/llvm-cov/html
